### ISSUE TITLE
Plugin does not compile

### ISSUE THREAD

**Issue by jbieler** [OlsonDigital/cq-component-maven-plugin#65]
The Plugin does not compile because the maven repository does not contain gradle-base-services-groovy in version 1.6. The minimum version for all of the gradle dependencies is 2.1.

Pull Request #64 fixes this error. Please pull.

**Comment by modeckimellett** [comment]
Hi @jbieler 

Do you have a custom settings.xml that's using a different repository list from the one specified in this project's pom.xml?

This project uses [repo.gradle.org](https://github.com/OlsonDigital/cq-component-maven-plugin/blob/4250b48a885982fdd15d8090c6cc837e8cd26204/pom.xml#L63) and [repo.spring.io](https://github.com/OlsonDigital/cq-component-maven-plugin/blob/4250b48a885982fdd15d8090c6cc837e8cd26204/pom.xml#L68) as its repositories rather than the standard maven nexus. You can see gradle-base-services-groovy version 1.6 in the spring.io repo [here](http://repo.spring.io/ext-release-local/org/gradle/gradle-base-services-groovy/1.6/). To compile it you'll need to ensure that you aren't overwriting the pom level repository settings.

Thanks!
